<?php

declare(strict_types=1);

namespace ZeroToProd\LaravelDeclaration\Internal\Commands;

use Composer\Autoload\ClassLoader;
use Illuminate\Console\Command;
use RuntimeException;
use ZeroToProd\LaravelDeclaration\Internal\SchemaGenerator;

/**
 * Regenerates `manifest.schema.json` from the projected classes. The scope lives in the schema it generates
 * (`x-manifest.classes`), nowhere else: on bootstrap it is the CLI arguments, on regeneration the prior file's list.
 *
 * @internal
 */
class GenerateManifestSchemaCommand extends Command
{
    /** @var string */
    protected $signature = 'declaration:generate-manifest-schema
        {classes?* : The native class FQCNs to project (default: the prior schema\'s x-manifest.classes)}
        {--from= : The prior schema whose curation re-merges (default: the --out file)}
        {--out= : Write to this path (default: the package root manifest.schema.json)}
        {--report : Print the curation-only and TODO keys, write nothing}
        {--check : Fail when the regenerated bytes differ from the --out file, write nothing}';

    /** @var array<int, string> */
    protected $aliases = ['laravel-declaration:generate-manifest-schema'];

    /** @var string */
    protected $description = 'Regenerate manifest.schema.json from the projected native classes';

    public function handle(): int
    {
        $out = is_string($this->option('out')) ? $this->option('out') : dirname(__DIR__, 3).'/manifest.schema.json';
        $from = is_string($this->option('from')) ? $this->option('from') : $out;

        $decoded = is_file($from) ? json_decode((string) file_get_contents($from), true, 512, JSON_THROW_ON_ERROR) : null; // Rule 3.3: native failure

        /** @var array<string, mixed>|null $prior */
        $prior = is_array($decoded) ? $decoded : null;

        /** @var list<class-string> $classes */
        $classes = $this->argument('classes');

        if ($classes === []) {
            $manifest = is_array($prior['x-manifest'] ?? null) ? $prior['x-manifest'] : [];
            $declared = $manifest['classes'] ?? [];

            /** @var list<class-string> $classes */
            $classes = is_array($declared) ? array_values($declared) : [];
        }

        if ($classes === []) {
            $this->components->error('No classes given and `'.$from.'` declares none under x-manifest.classes.');

            return self::FAILURE;
        }

        $locate = static function (string $fqcn): ?string {
            foreach (ClassLoader::getRegisteredLoaders() as $loader) {                    // keyed by vendor dir
                $path = $loader->findFile($fqcn);

                if (is_string($path) && is_file($path)) {
                    return $path;                                                         // Laravel's multi-prefix PSR-4 resolved here
                }
            }

            return null;
        };

        foreach ($classes as $class) {
            if ($locate($class) === null) {                                               // every class pre-flighted BEFORE any write
                $this->components->error("No source file for $class");

                return self::FAILURE;
            }
        }

        $source = static fn (string $fqcn): ?string => ($path = $locate($fqcn)) === null ? null : (string) file_get_contents($path); // the ONLY I/O lives in this closure

        [$schema, $report] = SchemaGenerator::generate($classes, $prior, $source);

        $encoded = SchemaGenerator::encode($schema);

        if ($this->option('report') === true) {
            foreach ($report as $section => $keys) {
                $this->components->twoColumnDetail($section, $keys === [] ? '-' : (string) count($keys));

                foreach ($keys as $key) {
                    $this->line('  '.$key);
                }
            }

            return self::SUCCESS;
        }

        if ($this->option('check') === true) {
            if (! is_file($out) || file_get_contents($out) !== $encoded) {
                $this->components->error('`'.$out.'` is out of date: run declaration:generate-manifest-schema.');

                return self::FAILURE;
            }

            $this->components->info('`'.$out.'` is up to date.');

            return self::SUCCESS;
        }

        if (file_put_contents($out, $encoded) === false) {
            throw new RuntimeException("Failed to write schema to `$out`.");
        }

        $this->components->info('Generated '.count($classes).' definitions into `'.$out.'`.');

        return self::SUCCESS;
    }
}
